sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.7
before_install:  
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-engine
script:
  - make gr-plugin
notifications:
  email:
    recipients:
      - eng@portworx.com
      - jobi@portworx.com
    on_success: always
    on_failure: always
